# @Author: fankang
# @Time: 2022/6/25 16:27

from configparser import ConfigParser
from Common import Log
import os


class Config:
    # values:
    TEST_ENVIRONMENT = "test"
    TEST_VERSION_CODE = "1.0"
    TEST_WEB_HOST = "https://www.bitmarttest.com/api/"
    TEST_WEB_FUTURES_HOST = "https://derivatives.bitmarttest.com/"
    TEST_TREAMS_HOST = "https://teams.bitmarttest.com/api-admin/v1/api/"
    TEST_TREAMS_FUTURES_HOST = "https://teams-futures.bitmarttest.com/api-admin/"
    TEST_AUTHORIZATION = ""
    TEST_TEAMS_AUTHORIZATION = "eyJoZWFkZXIiOnsidHlwIjoiQml0TWFydCIsImFsZyI6IlJTQTIwNDgifSwicGF5bG9hZCI6eyJqaWQiOiJlOTk5NmE2MjExMDE0NTE2YTIxZmExMzMxNzM2YjY5MSIsInZlcnNpb24iOiIyMDIyMDcwMSIsImV4cGlyZXNBdCI6MTY1NjcwNzQyMjUwOSwiYm0iOiI1MjI2NUI5NEQ0ODUwQkQ2MzVBMDRCRDM3NkI1QjMyMzNFODU1QzgxQTA5NkNGQTc1Qzk2N0ZBRjY2RUE3RTVFNzY1MEI0ODYzOTVDOTAwNkMwQzFBNDQzQkI5MDkwREE0M0NENjZDQjc3NDNCMzkzOUVBMzVERkI1MjVBRTA1NUUzNEJFMERENTIxQzgzNkM5Q0IzN0MwMTdCQkE2M0NGRkE0N0NBM0ExNTA4RjRDNzJBMDQ1NzVBMjM1QTc0RjI1RTJENkQxQjRBQkZERjlBM0RCMDVEREU2QThCMDQ1RDBEREU2NzAyQTkyQjlFRkRBOEEyRTdCQjY5RjkwNDkxMzBEQTI3N0Q3RUI1RUUzREU4RkU1MThBN0NDMEM3RjMxODU3OEU5ODM4QTU5MEExODk5NkFCNTc1NTU1QUZFMkRBNkNDOUZBOTY4NzU5NDMwQ0U4MkQ5N0M4RjBBOUE3RjUxOTA1QTRENjhBREM3RjUzM0ZBMzdFQkVFNkYzRjNEMjJBMjgxMDZEQTkzNEJDODQwMkNBMDNGOTU3Qzk2OTI5ODcxRkFCMUIxMkNFMEQ3Q0UxQ0I1ODg5Q0M5QjVDNEU2RTk3Q0Q3MzI4OUZFN0UxQ0RCM0FEMzg0RjI3MjAzQkE1MkI4ODAzQkFENkNBQ0MwRkZEQkNCQTM4MzMxRDkzMzk3NTUwMkU0QUU5QUU0QUI2QUVFN0YyOUVGMzg0REI5NTg4NDAyRTM5MjlCNTI0MjhBQkQ4NjQyNkFGMTUifSwic2lnbmF0dXJlIjoiTnhyR0dVR0ZaMmhHYXhjWFk4Tk1BV0czaDE1aEtDRHVEQUdwK1kwZzhTSkxKVzhjM0EvTFQzdzdaZEw1cG1JUmQ1RzdpV1lrYmJLSUdNY0NQRCtXQmxmN00vZElESUljbmVpM0FmbGJJSGVyb0UrT1BMMldoNUJISUFHdnlHSUgxNnJtZ290eTB4d3ViRG9uL2pUVUV1YzFJSTFRaVVhY3ZKbUJqTHp1blJDR3czTHR2S0NrV09RZ0lKSG55TFpqR044Ykthd0huS29UYlRVdGpNNXl1aFBiYjNqMG5kR2NYNElYaWhnTkZRcW1RbWdyRmV5d2EraXZVVG1wZjl0VTZESGVia3RoWmVMcmZIaHA5QUdHNkcvN2hLT2g2U2ZVUFdZTlByNkQ2MG0wdUJtVit2N01FL0xzeGJxcFludDNKMXUwL21LU0RUTTQycUlVWHJYSGlnPT0ifQ=="

    # [mail]
    VALUE_SMTP_SERVER = "smtpserver"
    VALUE_SENDER = "sender"
    VALUE_RECEIVER = "receiver"
    VALUE_USERNAME = "username"
    VALUE_PASSWORD = "password"

    path_dir = str(os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir)))

    def __init__(self):
        self.conf_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'config.ini')
        self.xml_report_path = Config.path_dir + '/Report/xml'
        self.html_report_path = Config.path_dir + '/Report/html'
